### ISSUE TITLE
Porting FFelfelani's code checklist

### ISSUE THREAD

**Issue by amansnama** [akhter0907/CTSM5.2.023#18]
### Modified files
These files have been modified by FFelfelani in `release-clm5.0.07`. We are porting it to `ctsm5.2.023`.

- [x] bld/namelist_files/
    - [x]    namelist_defaults_clm4_5.xml > namelist_defaults_ctsm.xml
    - [x]    namelist_definition_clm4_5.xml > namelist_definition_ctsm.xml
        
- [ ] src/biogeophys/
   - [x] #20
   - [ ]  GroundwaterMod.F90
   - [x]        HydrologyNoDrainageMod.F90
   - [x]        HydrologyDrainageMod.F90
   - [x] SoilHydrologyInitTimeConstMod.F90
   - [ ] #19
   - [x]        SoilHydrologyType.F90
   - [x]        SoilWaterMovementMod.F90
   - [ ] #24
        
- [ ] src/main/  
   - [x]      clm_driver.F90
   - [ ]        clm_intializeMod.F90 
   - [x]        clm_varctl.F90
   - [x]        ColumnType.F90 
   - [ ]        decompInitMod.F90 
   - [ ]        decompMod.F90 
   - [x]        GridcellType.F90 
   - [x]        initVerticalMod.F90 
   - [x]        lnd2atmMod.F90 

- [x] Builds
- [ ] Runs
